config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  resources :outfits
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: 'store'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/outfit.rb
class Outfit < ApplicationRecord
	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
		message: 'URL должен указывать на изображение формата GIF, JPG или PNG.'
	}

	def self.latest
		Outfit.order(:updated_at).last
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :set_outfit, only: [:show, :edit, :update, :destroy]

  # GET /outfits
  # GET /outfits.json
  def index
    @outfits = Outfit.all
  end

  # GET /outfits/1
  # GET /outfits/1.json
  def show
  end

  # GET /outfits/new
  def new
    @outfit = Outfit.new
  end

  # GET /outfits/1/edit
  def edit
  end

  # POST /outfits
  # POST /outfits.json
  def create
    @outfit = Outfit.new(outfit_params)

    respond_to do |format|
      if @outfit.save
        format.html { redirect_to @outfit, notice: 'Outfit was successfully created.' }
        format.json { render :show, status: :created, location: @outfit }
      else
        format.html { render :new }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outfits/1
  # PATCH/PUT /outfits/1.json
  def update
    respond_to do |format|
      if @outfit.update(outfit_params)
        format.html { redirect_to @outfit, notice: 'Outfit was successfully updated.' }
        format.json { render :show, status: :ok, location: @outfit }
      else
        format.html { render :edit }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outfits/1
  # DELETE /outfits/1.json
  def destroy
    @outfit.destroy
    respond_to do |format|
      format.html { redirect_to outfits_url, notice: 'Outfit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outfit
      @outfit = Outfit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outfit_params
      params.require(:outfit).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@outfits = Outfit.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Truestyle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <div id="banner">
      <%= image_tag("logo.png") %>
      <%= @page_title || "Pragmatic Bookshelf" %>
    </div>

    <div id="columns">
      <div id="side">
        <ul>
          <li><a href="http://www....">Home</a></li>
          <li><a href="http://www..../faq">Questions</a></li>
          <li><a href="http://www..../news">News</a></li>
          <li><a href="http://www..../contact">Contact</a></li>
        </ul>
        <p>
          Now --- <%= Time.now %>
        </p>
      </div>
      

      <div id="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/outfits/_form.html.erb
<%= form_with(model: outfit, local: true) do |form| %>
  <% if outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>

      <ul>
      <% outfit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 6 %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/outfits/edit.html.erb
<h1>Editing Outfit</h1>

<%= render 'form', outfit: @outfit %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/index.html.erb
<h1>Listing products</h1>
<table>
<% @outfits.each do |outfit| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
<td>
<%= image_tag(outfit.image_url, class: 'list_image') %>
</td>
<td class="list_description">
<dl>
<dt><%= outfit.title %></dt>
<dd><%= truncate(strip_tags(outfit.description),
length: 80) %></dd>
</dl>
</td>
<td class="list_actions">
<%= link_to 'Show', outfit %><br/>
<%= link_to 'Edit', edit_outfit_path(outfit) %><br/>
<%= link_to 'Destroy', outfit, method: :delete,
data: { confirm: 'Are you sure?' } %>
</td>
</tr>
<% end %>
</table>
<br />
<%= link_to 'New product', new_outfit_path %>

app/views/outfits/new.html.erb
<h1>New Outfit</h1>

<%= render 'form', outfit: @outfit %>

<%= link_to 'Back', outfits_path %>

app/views/outfits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @outfit.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @outfit.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @outfit.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @outfit.price %>
</p>

<%= link_to 'Edit', edit_outfit_path(@outfit) %> |
<%= link_to 'Back', outfits_path %>

app/views/store/index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<h1>Your Pragmatic Catalog</h1>
<% cache ['store', Outfit.latest] do %>
	<% @outfits.each do |outfit| %>
	<% cache ['entry', outfit] do %>
		<div class="entry">
			<%= image_tag(outfit.image_url) %>
			<h3><%= outfit.title %></h3>
			<%= sanitize(outfit.description) %>
			<div class="price_line">
				<span class="price"><%= number_to_currency(outfit.price, :unit=>'₴ ') %></span>
			</div>
		</div>
	<% end %>
	<% end %>
<% end %>